# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_sample',
                'doc_host': 'https://tauzen.github.io',
                'git_url': 'https://github.com/tauzen/nbdev_sample',
                'lib_path': 'nbdev_sample'},
  'syms': { 'nbdev_sample.card': { 'nbdev_sample.card.Card': ('card.html#card', 'nbdev_sample/card.py'),
                                   'nbdev_sample.card.Card.__init__': ('card.html#card.__init__', 'nbdev_sample/card.py'),
                                   'nbdev_sample.card.Card.__str__': ('card.html#card.__str__', 'nbdev_sample/card.py')},
            'nbdev_sample.core': {'nbdev_sample.core.foo': ('deck.html#foo', 'nbdev_sample/core.py')}}}
