# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_sample',
                'doc_host': 'https://tauzen.github.io',
                'git_url': 'https://github.com/tauzen/nbdev_sample',
                'lib_path': 'nbdev_sample'},
  'syms': {'nbdev_sample.core': {'nbdev_sample.core.foo': ('core.html#foo', 'nbdev_sample/core.py')}}}
